#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Lint staged files with ESLint
npx --no-install eslint --ignore-path .gitignore .

# Run CommitLint against the commit message
npx --no-install commitlint --edit "$1"

# Run tests (replace 'npm test' with the command you use to run tests)
npm test
